config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :trips

  post 'trips/:id/users' => 'trips#add_user', as: :join_trip
  delete 'trips/:id/users' => 'trips#delete_user', as: :leave_trip

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user

  has_many :trips_users, dependent: :destroy
  has_many :users, through: :trips_users

  validates :transit, inclusion: %w(Walk Car Bus Train)

  validates :available_seats, numericality: { greater_than: -1 }

  validates :driver_id, numericality: { only_integer: true }, if: :driver_id

  validate :validate_driver_id, if: :driver_id

  def seats_available?
    return true if !available_seats || available_seats > users.size
    false
  end

  def trip_upcoming?
    departure > DateTime.now
  end

  def future_trip?
    departure > DateTime.now
  end

  private

  def validate_driver_id
    errors.add(:driver_id, 'is invalid') unless User.exists?(driver_id)
    errors.add(:driver_id, 'does not have a car') unless
      User.exists?(id: driver_id, car: true)
  end
end

app/models/trips_user.rb
class TripsUser < ApplicationRecord
  belongs_to :user
  belongs_to :trip
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  include BCrypt
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 2 }
  validates :name, format: { with: /\A[A-Z].*/,
                             message: 'must start with a capital letter' }

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: /.@.+\..*/,
                              message:
                                'must be in the format username@website.tld' }

  validates :number_of_seats, numericality: { greater_than: 0 }, if: :car
  validates_presence_of :number_of_seats, if: :car

  has_many :trips, dependent: :destroy

  def password
    @password ||= Password.new(password_hash) unless password_hash.nil?
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def all_trips
    Trip.where(id: TripsUser.select('trip_id').where(user_id: id))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method def logged_in?
    session[:user_id] = nil unless User.exists?(session[:user_id])
    session[:user_id]
  end

  helper_method def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:name])
    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User was successfully logged in.'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to '/', notice: 'User was successfully logged out.'
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip,
                only: [:show, :edit, :update, :destroy, :add_user, :delete_user]

  # GET /trips
  # GET /trips.json
  def index
    @upcoming_trips =
      Trip.where('departure > ?', DateTime.now).order(departure: :asc)
    @previous_trips =
      Trip.where('departure < ?', DateTime.now).order(departure: :desc)
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @driver = User.find(@trip.driver_id) if @trip.driver_id
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
    @participants_with_cars =
      User.where(
        car: true, id: TripsUser.select('user_id').where(trip_id: @trip.id)
      )
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params.merge(user_id: current_user.id))
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /trips/:id/users
  def add_user
    if @trip.users.include? current_user
      redirect_to @trip, notice: 'User already in trip.'
    else
      @trip.users.append(current_user)
      redirect_to @trip, notice: 'User was successfully added to the trip.'
    end
  end

  # DELETE /trips/:id/users
  def delete_user
    user = TripsUser.find_by(user_id: current_user.id, trip_id: params[:id])
    if user.nil?
      redirect_to @trip, notice: 'User was not in the trip.'
    else
      user.destroy
      redirect_to @trip, notice: 'User was successfully removed from the trip.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_trip
    @trip = Trip.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trip_params
    params.require(:trip).permit(
      :user_id, :driver_id, :departure, :available_seats, :start_location,
      :end_location, :connection?, :transit, :cost
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :show_trips, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    trips = @user.all_trips
    @upcoming_trips =
      trips.where('departure > ?', DateTime.now).order(departure: :asc)
    @previous_trips =
      trips.where('departure < ?', DateTime.now).order(departure: :desc)
  end

  def show_trips
    render :show_trips
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    reset_session
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(
      :user
    ).permit(:name, :car, :number_of_seats, :email, :phone, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    return unless logged_in?
    trips = current_user.all_trips
    @upcoming_trips =
      trips.where('departure > ?', DateTime.now).order(departure: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">

    <div class="navbar-header">
      <a class="navbar-brand" href="#">TripTrap</a>
    </div>

      <a class="btn navbar-btn btn-default" href="/users">Users</a>
      <a class="btn navbar-btn btn-default" href="/trips">Trips</a>
      <!-- Add link to user's show page and log out button if logged in -->
      <% if logged_in? %>
        <a><%= link_to 'Log out', logout_path, method: :delete, class: 'btn navbar-btn btn-danger pull-right' %></a>
        <a><%= link_to current_user.name, current_user, class: 'btn navbar-btn btn-default pull-right' %></a>
        <a><%= link_to 'New Trip', new_trip_path, class: 'btn navbar-btn btn-default' %></a>
      <% else %>
        <a class='btn navbar-btn btn-success pull-right' href="/users/new">Sign up</a>
        <a class='btn navbar-btn btn-primary pull-right' href="/login">Log in</a>
      <% end %>
      <a class="btn navbar-btn btn-default pull-right" href="/">Home</a>
      <!-- Add log out link otherwise -->
      <span class="nav-sessions">
      </span>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripTrap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

  <%= render 'layouts/nav' %>

  <%= yield %>

  </body>
</html>

app/views/trips/_form.html.erb
<%= form_for(trip) do |f| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :departure %>
    <%= f.datetime_select :departure %>
  </div>

  <div class='form-group'>
    <%= f.label :start_location %>
    <%= f.text_field :start_location %>
  </div>

  <div class='form-group'>
    <%= f.label :end_location %>
    <%= f.text_field :end_location %>
  </div>

  <div class='form-inline'>
    <%= f.label :transit %>
    <%= f.select :transit, ['Walk', 'Car', 'Train', 'Bus']%>

  <% if trip.transit == 'Car' && @participants_with_cars.size > 0%>
      <%= f.label :driver_id %>
      <%= f.select :driver_id, @participants_with_cars.map {|p| [p.name, p.id]}%>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :available_seats %>
    <%= f.number_field :available_seats %>
  </div>

  <div class='form-group'>
    <strong> <%= f.label :cost %> (per person) </strong>
    $ <%= f.text_field :cost %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/_show_trips.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>Departure Time</th>
      <th>Trip</th>
      <th>Transit</th>
    </tr>
  </thead>
        
  <tbody>
    <% trips.each do |trip| %>  
      <tr>
        <td><%= trip.departure %></td>
        <td><%= trip.start_location %>
          <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
          <%= trip.end_location %></td>
        <td><%= trip.transit %></td>
        <td><%= link_to 'Show', trip, class: 'btn btn-default btn-xs' %>
        <% if trip.user == current_user %>
            <%= link_to 'Edit', edit_trip_path(trip), class: 'btn btn-default btn-xs' %>
            <%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
  
<br>

app/views/trips/edit.html.erb
<div class="col-md-4 col-md-offset-4">

  <h1 class='text-center'>Editing Trip</h1>

  <%= render 'form', trip: @trip %>

  <%= link_to 'Back to all trips', trips_path, class: 'pull-right' %>
  <a class='pull-right'>  |  </a>
  <%= link_to 'Show Trip', @trip, class: 'pull-right' %>

</div>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<h3>Upcoming Trips:</h3>
<%= render 'show_trips', trips: @upcoming_trips %>

<h3>Previous Trips:</h3>
<%= render 'show_trips', trips: @previous_trips %>

app/views/trips/new.html.erb
<div class="col-md-4 col-md-offset-4">

  <h1 class='text-center'>New Trip</h1>

  <%= render 'form', trip: @trip %>

  <%= link_to 'Back to all trips', trips_path, class: 'pull-right' %>

</div>

app/views/trips/show.html.erb
<div class="col-md-4 col-md-offset-4 text-center">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>User:</strong>
    <%=link_to @trip.user.name, @trip.user, class: 'btn btn-default btn-xs' %>
  </p>

  <p>
    <strong>Departure:</strong>
    <%= @trip.departure %>
  </p>

  <p>
    <strong>Start location:</strong>
    <%= @trip.start_location %>
  </p>

  <p>
    <strong>End location:</strong>
    <%= @trip.end_location %>
  </p>

  <p>
    <strong>Transit:</strong>
    <%= @trip.transit %>
    <% if @trip.driver_id %>
      <strong>Driver: </strong>
      <%= link_to @driver.name, @driver, class: 'btn btn-default btn-xs' %>
    <% end %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= @trip.cost %>
  </p>

  <p>
    <strong>Participants:</strong>
    <%= @trip.users.size %> / <%= @trip.available_seats %>

    <br>
      <tr>
        <% @trip.users.each do |user| %>
          <td><%= link_to user.name, user, class: 'btn btn-default btn-xs' %></td>
        <% end %>
      </tr>
  </p>

  <% unless @trip.user != current_user %>
    <%= link_to 'Edit', edit_trip_path(@trip), class: 'btn btn-default btn-xs' %> |
  <% end %>

  <% if logged_in? && @trip.seats_available? && @trip.trip_upcoming? %>
    <%= link_to 'Join', join_trip_path(@trip), method: :post, class: 'btn btn-success btn-xs' %> |
    <%= link_to 'Leave', leave_trip_path(@trip), method: :delete, class: 'btn btn-danger btn-xs' %> |
  <% end %>

  <%= link_to 'Back', trips_path, class: 'btn btn-default btn-xs' %>

</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :car %>
    <%= f.check_box :car %>
  </div>

  <div id="car_details" style="display:none;">
    <%= f.label :number_of_seats %>
    <%= f.number_field :number_of_seats %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  var checkbox = document.getElementById('user_car');
  var details_div = document.getElementById('car_details');
  checkbox.onchange = function() {
     if(this.checked) {
       details_div.style['display'] = 'block';
     } else {
       details_div.style['display'] = 'none';
     }
  };
</script>

app/views/users/edit.html.erb
<div class="col-md-4 col-md-offset-4 text-center">
  <h1>Editing User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Show', @user %> |
  <%= link_to 'All Users', users_path %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Car</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Newest Trip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user, class: 'btn btn-default btn-xs' %></td>
        <td><%= user.car %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <% unless user.trips.empty? %>
          <td><%= user.trips.last.start_location unless user.trips.empty? %>
              <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
              <%= user.trips.last.end_location unless user.trips.empty? %></td>
          <% end %>
        <% if user == current_user %>
          <td><%= link_to 'Show', user, class: 'btn btn-default btn-xs' %>
            <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-default btn-xs' %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Sign up!', new_user_path, class: 'btn btn-primary btn-xs text-center' unless logged_in? %>

app/views/users/new.html.erb
<div class="col-md-4 col-md-offset-4 text-center">
  <h1>New User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="col-md-4 col-md-offset-4 text-center">

  <p id="notice"><%= notice %></p>

  <p>
    <h1><%= @user.name %></h1>
  </p>


  <p>
    <h4>
      <strong>Car:</strong>

      <% if @user.car %>
        Yes
        <strong>Number of Seats:</strong>
        <%= @user.number_of_seats %>
      <% else %>
        No
      <% end %>
    </h4>
  </p>

  <p>
    <table class='table'>
      <thead>
        <tr>
          <th>Phone Number</th>
          <th>Email Address</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><%=@user.phone%></th>
          <th><%=@user.email%></th>
        </tr>
      </tbody>
    </table>
  </p>

  <h3>Upcoming Trips:</h3>
  <%= render 'trips/show_trips', trips: @upcoming_trips %>

  <h3>Previous Trips:</h3>
  <%= render 'trips/show_trips', trips: @previous_trips %>

  <% if @user == current_user %>
    <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-default btn-xs' %> |
    <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %> |
  <% end %>

  <%= link_to 'Back', users_path, class: 'btn btn-default btn-xs' %>

</div>

app/views/welcome/index.html.erb
<h1 class="welcome-banner text-center">Welcome to TripTrap!</h1>
<!-- TODO: Greet the current user! -->
<% if logged_in? %>
  <h2>Hi <%= current_user.name %></h2>
  <h3>Upcoming Trips:</h3>
  <%= render 'trips/show_trips', trips: @upcoming_trips %>
<% else %>
  <div class="col-md-4 col-md-offset-4 text-center">
    <h2>What's black and white and red all over?</h2>
    <h4> TripTrap! The solution for all your trip organizing needs.</h4>
    <p>
      You might not see it now, but that's because you haven't made a splendiferiffic account yet. Why should you, I hear you cry. Elementary, my dear Watson! Or whatever your name is. Have you ever wanted to go on a trip, but didn't want to go alone? Or you needed a driver, but didn't want it to be a total stranger? Enter TripTrap, the web app that allows you to choose your trip, choose a driver, and have fun!
    </p>
  </div>
<% end %>